## Importing and Organizing Your Data in Python - Part I

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

a. Create a series object of 10 randomly generated integer values.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ser = pd.Series(np.random.randint(10, size = 10, dtype = 'int'), name = "Column 01")

In [ ]:
ser

0    1
1    1
2    9
3    5
4    9
5    1
6    8
7    3
8    4
9    2
Name: Column 01, dtype: int64

b. Extract data from Yahoo Finance for Ford from the 1st of January 2005. The ticker you need is ‘F’.

In [ ]:
!pip install alpaca-trade-api

Requirement already satisfied: alpaca-trade-api in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.0.2)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (3.11.15)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.20.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)

In [ ]:
import alpaca_trade_api as alpaca

api = alpaca.REST('PKSVKIO35NZMZK00L2Z3', 'ifYF17huHaOsPFqbfkrPGbI9VMxPMHq36RZXJ9np', 'https://paper-api.alpaca.markets')

In [ ]:
f = api.get_bars('F', "1Month", start='2024-06-01', end='2025-06-30').df

In [ ]:
f

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2024-06-01 04:00:00+00:00,12.54,12.620,11.5500,1944773,12.25,883337188,12.082286
2024-07-01 04:00:00+00:00,10.82,14.850,10.7200,3268786,12.56,1532171937,12.762234
2024-08-01 04:00:00+00:00,11.19,11.370,9.4900,2595496,10.86,1264929933,10.387218
2024-09-01 04:00:00+00:00,10.56,11.310,10.1300,2135390,11.08,1004648814,10.724972
2024-10-01 04:00:00+00:00,10.29,11.390,10.1800,2531129,10.72,1196664326,10.738673
2024-11-01 04:00:00+00:00,11.13,11.520,10.2000,2338084,10.33,1096046703,10.990180
2024-12-01 05:00:00+00:00,9.90,11.245,9.6600,2536198,11.22,1218746882,10.213231
2025-01-01 05:00:00+00:00,10.08,10.450,9.5300,2525210,9.91,1330795941,10.001519
2025-02-01 05:00:00+00:00,9.55,10.315,9.1000,3004398,9.72,1675504566,9.483422
2025-03-01 05:00:00+00:00,10.03,10.400,9.0600,3761004,9.71,3012507193,9.822318
2025-04-01 04:00:00+00:00,10.01,10.270,8.4406,4186433,10.10,3137291905,9.553469
2025-05-01 04:00:00+00:00,10.38,10.840,10.0200,2880941,10.14,1983204756,10.413541
2025-06-01 04:00:00+00:00,10.85,10.920,9.8800,2608137,10.27,2046814451,10.448047