## Calculating Portfolio Risk

Calculate the risk of an equally weighted portfolio composed of Microsoft and Apple. The data can be obtained from *MSFT_AAPL_2000_2017.csv*.

*Hint: The code we went through in the lecture is what you need here. You will need to import the data first. The previous lessons could be a good reference point for that! :) *

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

sec_data = pd.read_csv('Dataset\MSFT_AAPL_2000_2017.csv', index_col='Date')
sec_returns = np.log(sec_data / sec_data.shift(1))
print (sec_data.head())

                 MSFT      AAPL
Date
1999-12-31  38.965767  3.303425
2000-01-03  38.903194  3.596616
2000-01-04  37.589046  3.293384
2000-01-05  37.985374  3.341579
2000-01-06  36.712940  3.052405

## MSFT

In [6]:
print ("mean:" , sec_returns['MSFT'].mean() * 250)
print ("std:" , sec_returns['MSFT'].std() * 250 ** 0.5)

mean: 0.028771781450598173
std: 0.3108036510677075

## Apple

In [4]:
print ("mean:" , sec_returns['AAPL'].mean() * 250)
print ("std:" , sec_returns['AAPL'].std() * 250 ** 0.5)

mean: 0.21608551229758935
std: 0.43895472339059527

***

## Covariance and Correlation


\begin{eqnarray*}
Covariance Matrix: \  \   
\Sigma = \begin{bmatrix}
        \sigma_{1}^2 \ \sigma_{12} \ \dots \ \sigma_{1I} \\
        \sigma_{21} \ \sigma_{2}^2 \ \dots \ \sigma_{2I} \\
        \vdots \ \vdots \ \ddots \ \vdots \\
        \sigma_{I1} \ \sigma_{I2} \ \dots \ \sigma_{I}^2
    \end{bmatrix}
\end{eqnarray*}

*****

Covariance matrix:

In [7]:
cov_matrix = sec_returns.cov() * 250
cov_matrix

          MSFT      AAPL
MSFT  0.096599  0.054592
AAPL  0.054592  0.192681

***

Correlation matrix:

In [8]:
corr_matrix = sec_returns.corr()
corr_matrix

          MSFT      AAPL
MSFT  1.000000  0.400153
AAPL  0.400153  1.000000

## Calculating Portfolio Risk

Equal weigthing scheme:

In [9]:
weights = np.array([0.5, 0.5])

Portfolio Variance:

In [ ]:
cov_matrix = sec_returns.cov() * 250
cov_matrix

np.float64(0.09961622870546066)

Portfolio Volatility:

In [1]:
#pfolio_vol = np.dot(weights, np.dot(cov_matrix, weights)) ** 0.5
pfolio_vol = pfolio_var ** 0.5
pfolio_vol

NameError: name 'pfolio_var' is not defined

In [15]:
print (str(round(pfolio_vol, 5) * 100) + '%')

31.562%